name: Deploy Images to google drive

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag crpi-7ktbj4velv7hj2iv.cn-hangzhou.personal.cr.aliyuncs.com/fashionnew/firecrawl:latest
          - name: 'set ps1'
            run: |
              cat ~/.docker/config.json
          - name: 'set ps'
            run: |
              echo '{"auths": {"crpi-7ktbj4velv7hj2iv.cn-hangzhou.personal.cr.aliyuncs.com": {"auth": "'$AUTH_STRING'"}}}' > ~/.docker/config.json
          - name: 'Push Image 2 ali acr'
            run: |
              docker push crpi-7ktbj4velv7hj2iv.cn-hangzhou.personal.cr.aliyuncs.com/fashionnew/firecrawl:latest


