name: Deploy Images to google drive

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/fashionnew/firecrawl:latest 
              docker save -o firecrawl.tar ghcr.io/fashionnew/firecrawl:latest 

          - name: Upload to Google Drive
            id: upload
	      uses: iterative/google-drive-upload-action@v1
	      with:
              parent_folder_id: ${{ secrets.PARENT_FOLDER_ID }}
              files: 'firecrawl.tar'
              credentials_json: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
