name: Deploy Images to google drive

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/fashionnew/firecrawl:latest 

          - name: 'Save Image'
            run: |
              docker save -o firecrawl.tar.gz ghcr.io/fashionnew/firecrawl:latest 

          - name: Upload to gdrive
            uses: mathisve/gdrive-upload-action@main
            with:
              filename: firecrawl.tar.gz
              name: firecrawl.tar.gz
              folderId: ${{ secrets.PARENT_FOLDER_ID }}
              credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
              encoded: false
