name: Deploy Images to ali

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ${{secrets.REGISTRY}}
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ${{secrets.REGISTRY}}/fashionnew/firecrawl:latest
          - name: 'get ps1'
            run: |
              cat ~/.docker/config.json
          - name: 'Push Image 2 ali acr'
            run: |
              docker push ${{secrets.REGISTRY}}/fashionnew/firecrawl:latest


